/***************************************************************************
 * EnvExporter implementation
 ***************************************************************************/

#import "EnvExporter.h"

#import <AppKit/AppKit.h>

@implementation EnvExporter

+ (NSString *)activeShellDirectory
{
	return [NSHomeDirectory() stringByAppendingPathComponent:@".envmask"];
}

+ (NSString *)activeZshPath
{
	return [[self activeShellDirectory] stringByAppendingPathComponent:@"active.zsh"];
}

+ (NSString *)escapeSingleQuotes:(NSString *)s
{
	// POSIX-safe single-quote escaping:  abc'd -> 'abc'"'"'d'
	return [s stringByReplacingOccurrencesOfString:@"'" withString:@"'\"'\"'"];
}

+ (NSString *)formatZshExportScriptFromEnv:(NSDictionary<NSString *, NSString *> *)env
{
	NSMutableString *out = [NSMutableString string];
	[out appendString:@"# Generated by EnvMask (v1)\n"];
	[out appendString:@"# Usage: source ~/.envmask/active.zsh\n\n"];

	NSArray *keys = [[env allKeys] sortedArrayUsingSelector:@selector(compare:)];
	for (NSString *key in keys) {
		NSString *val = env[key] ?: @"";
		NSString *escaped = [self escapeSingleQuotes:val];
		[out appendFormat:@"export %@='%@'\n", key, escaped];
	}
	return out;
}

+ (BOOL)ensureDirExists:(NSError **)error
{
	NSFileManager *fm = [NSFileManager defaultManager];
	NSString *dir = [self activeShellDirectory];
	BOOL isDir = NO;
	if ([fm fileExistsAtPath:dir isDirectory:&isDir]) {
		return isDir;
	}
	return [fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:error];
}

+ (BOOL)writeActiveZshFromEnv:(NSDictionary<NSString *, NSString *> *)env error:(NSError **)error
{
	if (![self ensureDirExists:error]) {
		return NO;
	}

	NSString *script = [self formatZshExportScriptFromEnv:env];
	NSString *path = [self activeZshPath];
	return [script writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:error];
}

+ (void)openActiveZshInFinder
{
	[[NSWorkspace sharedWorkspace] activateFileViewerSelectingURLs:@[[NSURL fileURLWithPath:[self activeZshPath]]]];
}

+ (void)copySourceCommandToPasteboard
{
	NSString *cmd = [NSString stringWithFormat:@"source %@", [self activeZshPath]];
	NSPasteboard *pb = [NSPasteboard generalPasteboard];
	[pb clearContents];
	[pb setString:cmd forType:NSPasteboardTypeString];
}

+ (NSString *)zshrcPath
{
	return [NSHomeDirectory() stringByAppendingPathComponent:@".zshrc"];
}

+ (NSString *)zshrcBackupPath
{
	return [NSHomeDirectory() stringByAppendingPathComponent:@".zshrc.envmask.bak"];
}

+ (NSString *)cursorSettingsPath
{
	// Cursor follows VS Code settings location convention.
	return [NSHomeDirectory() stringByAppendingPathComponent:@"Library/Application Support/Cursor/User/settings.json"];
}

+ (NSArray<NSString *> *)zdotdirsFromCursorSettings
{
	NSString *path = [self cursorSettingsPath];
	NSData *data = [NSData dataWithContentsOfFile:path options:0 error:NULL];
	if (!data) return @[];

	id json = [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL];
	if (![json isKindOfClass:[NSDictionary class]]) return @[];

	NSDictionary *root = (NSDictionary *)json;
	id profiles = root[@"terminal.integrated.profiles.osx"];
	if (![profiles isKindOfClass:[NSDictionary class]]) return @[];

	NSMutableOrderedSet<NSString *> *dirs = [NSMutableOrderedSet orderedSet];
	for (id key in (NSDictionary *)profiles) {
		id profile = ((NSDictionary *)profiles)[key];
		if (![profile isKindOfClass:[NSDictionary class]]) continue;
		id env = ((NSDictionary *)profile)[@"env"];
		if (![env isKindOfClass:[NSDictionary class]]) continue;
		id zdotdir = ((NSDictionary *)env)[@"ZDOTDIR"];
		if (![zdotdir isKindOfClass:[NSString class]]) continue;

		NSString *s = [(NSString *)zdotdir stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
		if ([s length] == 0) continue;
		[dirs addObject:s];
	}
	return [dirs array];
}

+ (NSArray<NSString *> *)zshrcPathsForAutoApply
{
	NSMutableOrderedSet<NSString *> *paths = [NSMutableOrderedSet orderedSet];
	[paths addObject:[self zshrcPath]];

	NSArray<NSString *> *zdotdirs = [self zdotdirsFromCursorSettings];
	for (NSString *dir in zdotdirs) {
		NSString *zshrc = [dir stringByAppendingPathComponent:@".zshrc"];
		[paths addObject:zshrc];
	}
	return [paths array];
}

+ (BOOL)ensureParentDirectoryExistsForFilePath:(NSString *)filePath error:(NSError **)error
{
	NSString *parent = [filePath stringByDeletingLastPathComponent];
	if (!parent || [parent length] == 0) return YES;

	NSFileManager *fm = [NSFileManager defaultManager];
	BOOL isDir = NO;
	if ([fm fileExistsAtPath:parent isDirectory:&isDir]) {
		return isDir;
	}
	return [fm createDirectoryAtPath:parent withIntermediateDirectories:YES attributes:nil error:error];
}

+ (NSString *)managedZshrcLine
{
	// keep it simple and grep-friendly
	return @"source ~/.envmask/active.zsh  # envmask";
}

+ (BOOL)isZshrcInstalled
{
	NSArray<NSString *> *paths = [self zshrcPathsForAutoApply];
	if ([paths count] == 0) return NO;

	for (NSString *path in paths) {
		NSString *txt = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:NULL];
		if (!txt) return NO;
		if ([txt rangeOfString:[self managedZshrcLine]].location == NSNotFound) return NO;
	}
	return YES;
}

+ (BOOL)installToZshrc:(NSError **)error
{
	NSFileManager *fm = [NSFileManager defaultManager];
	NSArray<NSString *> *paths = [self zshrcPathsForAutoApply];
	BOOL allOk = YES;

	for (NSString *path in paths) {
		NSError *dirErr = nil;
		if (![self ensureParentDirectoryExistsForFilePath:path error:&dirErr]) {
			allOk = NO;
			if (error && *error == nil) *error = dirErr;
			continue;
		}

		NSString *txt = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:NULL];
		if (!txt) txt = @"";

		if ([txt rangeOfString:[self managedZshrcLine]].location != NSNotFound) {
			continue;
		}

		// Backup best-effort (only for the default ~/.zshrc, keep behavior stable)
		if ([path isEqualToString:[self zshrcPath]] && [fm fileExistsAtPath:path] && ![fm fileExistsAtPath:[self zshrcBackupPath]]) {
			[fm copyItemAtPath:path toPath:[self zshrcBackupPath] error:NULL];
		}

		NSMutableString *out = [txt mutableCopy];
		if ([out length] > 0 && ![out hasSuffix:@"\n"]) {
			[out appendString:@"\n"];
		}
		[out appendString:@"\n# EnvMask (managed)\n"];
		[out appendFormat:@"%@\n", [self managedZshrcLine]];

		NSError *writeErr = nil;
		if (![out writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:&writeErr]) {
			allOk = NO;
			if (error && *error == nil) *error = writeErr;
		}
	}
	return allOk;
}

+ (BOOL)uninstallFromZshrc:(NSError **)error
{
	NSArray<NSString *> *paths = [self zshrcPathsForAutoApply];
	BOOL allOk = YES;

	for (NSString *path in paths) {
		NSString *txt = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:NULL];
		if (!txt) continue;

		if ([txt rangeOfString:[self managedZshrcLine]].location == NSNotFound) {
			continue;
		}

		NSArray<NSString *> *lines = [txt componentsSeparatedByString:@"\n"];
		NSMutableArray<NSString *> *kept = [NSMutableArray arrayWithCapacity:[lines count]];

		for (NSString *line in lines) {
			if ([line isEqualToString:[self managedZshrcLine]]) continue;
			if ([line isEqualToString:@"# EnvMask (managed)"]) continue;
			[kept addObject:line];
		}

		NSString *out = [kept componentsJoinedByString:@"\n"];
		NSError *writeErr = nil;
		if (![out writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:&writeErr]) {
			allOk = NO;
			if (error && *error == nil) *error = writeErr;
		}
	}
	return allOk;
}

@end

