/***************************************************************************
 * EnvLauncherGenerator implementation
 ***************************************************************************/

#import "EnvLauncherGenerator.h"

#import "EnvStore.h"

@implementation EnvLauncherGenerator

+ (NSString *)launchersDirectoryInStore
{
	return [[[EnvStore defaultInstance] rootDirectory] stringByAppendingPathComponent:@"Launchers"];
}

+ (BOOL)ensureLaunchersDirectoryExists:(NSError **)error
{
	NSFileManager *fm = [NSFileManager defaultManager];
	NSString *dir = [self launchersDirectoryInStore];
	BOOL isDir = NO;
	if ([fm fileExistsAtPath:dir isDirectory:&isDir]) {
		return isDir;
	}
	return [fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:error];
}

+ (NSString *)sanitizeFileName:(NSString *)name
{
	NSCharacterSet *invalid = [[NSCharacterSet characterSetWithCharactersInString:@"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_(). "] invertedSet];
	NSArray *parts = [name componentsSeparatedByCharactersInSet:invalid];
	NSString *joined = [parts componentsJoinedByString:@"_"];
	NSString *trim = [joined stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
	return ([trim length] > 0) ? trim : @"launcher";
}

+ (NSString *)escapeForSingleQuotedShell:(NSString *)s
{
	return [s stringByReplacingOccurrencesOfString:@"'" withString:@"'\"'\"'"];
}

+ (NSString *)createCommandLauncherWithName:(NSString *)name
							 executablePath:(NSString *)executablePath
										env:(NSDictionary<NSString *, NSString *> *)env
									  error:(NSError **)error
{
	if (![self ensureLaunchersDirectoryExists:error]) {
		return nil;
	}

	NSString *safe = [self sanitizeFileName:(name ?: @"launcher")];
	NSString *path = [[self launchersDirectoryInStore] stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.command", safe]];

	NSMutableString *script = [NSMutableString string];
	[script appendString:@"#!/bin/zsh\n"];
	[script appendString:@"set -euo pipefail\n\n"];

	// Start from a clean env for determinism; keep minimal essentials.
	[script appendString:@"# Generated by EnvMask (v1)\n"];
	[script appendString:@"# Launch target with injected environment\n\n"];

	// Compose env -i KEY='VAL' ... -- <exe>
	[script appendString:@"/usr/bin/env -i \\\n"];

	NSArray *keys = [[env allKeys] sortedArrayUsingSelector:@selector(compare:)];
	for (NSString *key in keys) {
		NSString *val = env[key] ?: @"";
		NSString *escaped = [self escapeForSingleQuotedShell:val];
		[script appendFormat:@"  %@='%@' \\\n", key, escaped];
	}

	NSString *escapedExe = [self escapeForSingleQuotedShell:(executablePath ?: @"")];
	[script appendFormat:@"  -- '%@'\n", escapedExe];

	if (![script writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:error]) {
		return nil;
	}

	// Make executable
	NSDictionary *attrs = @{NSFilePosixPermissions: @(0755)};
	[[NSFileManager defaultManager] setAttributes:attrs ofItemAtPath:path error:NULL];
	return path;
}

@end

